//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AvargeUserRating
    {
        public int idUserSeller { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> BuyerService { get; set; }
        public Nullable<decimal> TrueDescription { get; set; }
        public Nullable<decimal> ShippingTime { get; set; }
    }
}
