//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityRanking
    {
        public string Town { get; set; }
        public Nullable<int> DeliveredOrders { get; set; }
        public Nullable<int> ShippedOrdes { get; set; }
        public Nullable<int> Users { get; set; }
    }
}
