//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int idLogin { get; set; }
        public int idUser { get; set; }
        public System.DateTime date { get; set; }
        public string device { get; set; }
    
        public virtual User User { get; set; }
    }
}
