//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.Rating = new HashSet<Rating>();
        }
    
        public int idPurchase { get; set; }
        public int idUser { get; set; }
        public int idAuction { get; set; }
        public int idPaymentMethod { get; set; }
        public int idDeliveryMethod { get; set; }
        public int idBuyerAddress { get; set; }
        public int idSellerAddress { get; set; }
        public int idPurchaseStatus { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual Address AddressBuyer { get; set; }
        public virtual Address AddressSeller { get; set; }
        public virtual Auction Auction { get; set; }
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
        public virtual PurchaseStatus PurchaseStatus { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Rating { get; set; }
    }
}
