//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionSite.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int idRating { get; set; }
        public System.DateTime date { get; set; }
        public int buyerService { get; set; }
        public int trueDescription { get; set; }
        public int shippingTime { get; set; }
        public int idPurchase { get; set; }
    
        public virtual Purchase Purchase { get; set; }
    }
}
